### ISSUE TITLE
feat: [anthos-bm-gcp-terraform] Updates to init_args trigger instance rebuild

### ISSUE THREAD

**Issue by apeabody** [GoogleCloudPlatform/anthos-samples#256]
It might be nice to have updates to [init_args ](https://github.com/GoogleCloudPlatform/anthos-samples/blob/945adb00ff153d114ddef4a6f73591d9b485152b/anthos-bm-gcp-terraform/main.tf#L280) trigger a rebuild of the instances to keep the state consistent.

**Comment by bourgeoisor** [comment]
@apeabody is this issue still relevant?

**Comment by apeabody** [comment]
Hi @bourgeoisor - This is still relevant, however not a priority unless there is a requirement from others to update the init_args_file file without a full destroy/create of the stack or similar workaround.

**Comment by NimJay** [comment]
Commenting since this is near out-of-SLO:
* The existing priority `p3` makes sense given the previous comment (i.e., there isn't explicit user demand).
* Unless this feature is added by someone already familiar with this specific sample (Andrew/Shabir/etc.), this would be a large effort — because onboarding to/understanding the sample is a big effort.

**Comment by apeabody** [comment]
Would need to update terraform-google-modules/vm/google//modules/compute_instance to handle lifecycle block.
