### ISSUE TITLE
cleanup: add ABM version grid table

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/anthos-samples#304]
### Description
- Currently we trigger releases based on release-please suggestion
- There is no parity between the release version and the ABM version or the TF version used
- Sometimes the repo is released minor version for the patch update for ABM
- So it might be useful to have a matrix showing how versions changed until now
- In addition it might be nice if we can match minot version updates to only Anthos/ABM version updates and patch version updates for the patches

**Comment by ahrarmonsur** [comment]
This is still in our backlog. Cooling off OSLO timer.

**Comment by NimJay** [comment]
**Update to cool down out-of-SLO list:**
I don't believe progress has been made on this effort.

**Comment by Shabirmean** [comment]
Yes, this is still relevant. But is not scheduled for work atleast until the end of Q3-23

**Comment by NimJay** [comment]
Comment since this is near out-of-SLO:
* Thanks, @Shabirmean, for the detailed issue description — super helpful.
* If I understand correctly, this is a complex effort.
     * For instance, does this mean that — in a given release of this repo — all samples should be using the same version of Terraform and/or ABM version?
* I wonder if the value-to-effort ratio is truly worth it.
* I also don't know if users are super conscious of the [release numbers of this repository](https://github.com/GoogleCloudPlatform/anthos-samples/releases).
    * As a user, I only care about a single sample at a time (specific folder — not the entire repo as a whole). If I want to locate a version of the sample that targets a specific version of ABM and or Terraform, I would check the git history/blame.
* I will leave this open since this is an interesting idea. But we should consider closing this the next time it reaches (near) out-of-SLO.

(@Shabirmean, correct me if any of my assumptions are wrong — you understand this repo and its users much better than I do. 😄 )

**Comment by Shabirmean** [comment]
Hey @NimJay 

Thank you very much for TAL at this issue. I also agree with all your points. The issue was created during the early stages of ABM samples being added to this repo. I did not have a clear oversight into how this repo might be used by stakeholders. Now that we have added many samples and have some data about the interaction, I agree that the whole effort is not very useful.

However, one key thing to consider is that with newer features being added, a customer who is using an older version might want to try the sample without having to configure things for new features. In that case it helps to have a simple matrix of ABM version to repo version - allowing the stakeholder to checkout the repo at the required tag and use the sample. I would suggest atleast aiming for that Matrix and not doing any other major release specific changes.

I will let the current repo owners, decide on whether to prioritize it or not!
