### ISSUE TITLE
"Error: Unsupported Terraform Core version" - 0.14.9

### ISSUE THREAD

**Issue by tiny-tinker** [GoogleCloudPlatform/anthos-samples#56]
Running the `terraform init` command gives this:

```bash
Initializing modules...
╷
│ Error: Unsupported Terraform Core version
│
│   on versions.tf line 28, in terraform:
│   28:   required_version = "~> 0.14.9"
│
│ This configuration does not support Terraform version 1.0.0. To proceed, either choose another supported
│ Terraform version or update this version constraint. Version constraints are normally set for good reason, so
│ updating the constraint may lead to other errors or unexpected behavior.
╵
```

I'm running terraform 1.0.0, but also got this error when running 0.14.8. It looks like the `required_version` just needs to be bumped. I'll poke at it and create a PR if I'm successful.

**Comment by Shabirmean** [comment]
Hello @tiny-tinker 
Thank you very much for trying the sample out and raising this issue. Currently the sample has only been tested for support with the [**increment** to the patch version](https://www.terraform.io/docs/language/expressions/version-constraints.html#gt--1). 

We will work on ensuring support with the latest TF versions. Some of the modules need to be updated to enable this

**Comment by Shabirmean** [comment]
@tiny-tinker - we have bound the repo to exact versions given that breaking changes in Terraform itself was resulting in the samples to break. 

However, since `v1.0.0` it seems like it is safe to specify a `version range` instead of a specific version. The current master supports TF version ranges `>= 0.15.5, < 1.1`. We will continue to update this as we test the samples with new releases of Terraform
